### ISSUE TITLE
CPAN test fails

### ISSUE THREAD

**Issue by dtaust** [nicklangridge/WebService-Spotify#3]
At line 97 in live.t this is causing a failed test when installing with cpan:
`my $result = $spotify->search('weezer pinkerton', type => 'track');`
pretty sure this should be 
`my $result = $spotify->search('el scorcho', type => 'track');`

CPAN Log:
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/live.t .. 27/?
#   Failed test 'found track El Scorcho'
#   at t/live.t line 100.
#          got: 'The Good Life'
#     expected: 'El Scorcho'
t/live.t .. 31/? # Looks like you failed 1 test of 32.

**Comment by nicklangridge** [comment]
Fixed with https://github.com/nicklangridge/WebService-Spotify/commit/d4ed3dc462f187657ffd9b3efdd2954c6916c6c0
